### ISSUE TITLE
After Updating with your Flash script the Website http://192.168.XXX.225:2023 is not opening

### ISSUE THREAD

**Issue by Pretender1988** [AWSW-de/AWSW-ESP32-flash-script#1]
Hi,
i do not know how and where to content you but I like your work!
Many thanks!

I am struggling with the http requests to remotely change settings. Can you provide me a better example via CMD or something?
When I open the Website http://192.168.XXX.225:2023 I do not get any response. Is that expected?

**Comment by Pretender1988** [comment]
The issue was my Network :)

Is there a reason why the wordclock 2024 code is not accessible anymore?

**Comment by AWSW-de** [comment]
Hi,
please see FAQ on printables.  

Thanks and I will close this issue. 

Kind regards
